#ifndef __AI_CORE_INFER_ERROR_CODE_HPP__
#define __AI_CORE_INFER_ERROR_CODE_HPP__

#include <cstdint> // For int32_t

namespace ai_core {

enum class InferErrorCode : int32_t {
  SUCCESS = 0,

  // init error
  INIT_FAILED = 100,
  INIT_CONFIG_FAILED = 101,
  INIT_MODEL_LOAD_FAILED = 102,
  INIT_DEVICE_FAILED = 103,
  INIT_MEMORY_ALLOC_FAILED = 104,
  INIT_DECRYPTION_FAILED = 105,
  NOT_INITIALIZED = 106,

  // infer error
  INFER_FAILED = 200,
  INFER_INPUT_ERROR = 201,
  INFER_OUTPUT_ERROR = 202,
  INFER_DEVICE_ERROR = 203,
  INFER_PREPROCESS_FAILED = 204,
  INFER_MEMORY_ERROR = 205,
  INFER_SET_INPUT_FAILED = 206,
  INFER_EXTRACT_FAILED = 207,
  INFER_UNSUPPORTED_OUTPUT_TYPE = 208,

  // release error
  TERMINATE_FAILED = 300,

  // algo manager error
  ALGO_NOT_FOUND = 400,
  ALGO_REGISTER_FAILED = 401,
  ALGO_UNREGISTER_FAILED = 402,
  ALGO_INFER_FAILED = 403,
};

} // namespace ai_core
#endif // __AI_CORE_INFER_ERROR_CODE_HPP__
