#ifndef __AI_CORE_INFER_ERROR_CODE_HPP__
#define __AI_CORE_INFER_ERROR_CODE_HPP__
#include <cstdint>

namespace ai_core {

enum class InferErrorCode : int32_t {
  SUCCESS = 0,

  // init error
  INIT_FAILED = 100,
  INIT_CONFIG_FAILED = 101,
  INIT_MODEL_LOAD_FAILED = 102,
  INIT_DEVICE_FAILED = 103,
  INIT_MEMORY_ALLOC_FAILED = 104,
  INIT_DECRYPTION_FAILED = 105,
  NOT_INITIALIZED = 106,
  INIT_RUNTIME_FAILED = 107,
  INIT_ENGINE_FAILED = 108,
  INIT_CONTEXT_FAILED = 109,
  INIT_BINDING_FAILED = 110,

  // infer error
  INFER_FAILED = 200,
  INFER_INPUT_ERROR = 201,
  INFER_OUTPUT_ERROR = 202,
  INFER_DEVICE_ERROR = 203,
  INFER_PREPROCESS_FAILED = 204,
  INFER_MEMORY_ERROR = 205,
  INFER_SET_INPUT_FAILED = 206,
  INFER_EXTRACT_FAILED = 207,
  INFER_UNSUPPORTED_OUTPUT_TYPE = 208,
  INFER_TYPE_MISMATCH = 209,
  INFER_SIZE_MISMATCH = 210,
  INFER_INVALID_INPUT = 211,
  INFER_EXECUTION_FAILED = 212,
  INFER_BINDING_ERROR = 213,

  // release error
  TERMINATE_FAILED = 300,

  // algo manager error
  ALGO_NOT_FOUND = 400,
  ALGO_REGISTER_FAILED = 401,
  ALGO_UNREGISTER_FAILED = 402,
  ALGO_INFER_FAILED = 403,
};

} // namespace ai_core
#endif // __AI_CORE_INFER_ERROR_CODE_HPP__
